name: riverpod_bug_repro
description: A possible bug?

publish_to: 'none' # DO NOT remove this, unless you wish to publish this package

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# I know, I know, so many dependencies.
dependencies:
  flutter:
    sdk: flutter
  go_router: ^5.0.5
  hooks_riverpod: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
